# Generated by Django 4.0.3 on 2022-07-29 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('N_lot', models.CharField(max_length=1000, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='VracModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('Non Sensible', 'Non Sensible'), ('Sensible', 'Sensible')], max_length=200)),
                ('forme', models.CharField(blank=True, max_length=2000, null=True)),
                ('quantité', models.FloatField(blank=True, null=True)),
                ('n_sac', models.IntegerField(blank=True, null=True)),
                ('emplacement', models.CharField(blank=True, max_length=200, null=True)),
                ('agent', models.CharField(blank=True, max_length=200, null=True)),
                ('d_sortie', models.DateTimeField(blank=True, null=True)),
                ('d_entre', models.DateTimeField(blank=True, null=True)),
                ('qu', models.FloatField(blank=True, null=True)),
                ('N_Lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='saisir.lot')),
            ],
        ),
        migrations.CreateModel(
            name='SechageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operateur', models.CharField(blank=True, max_length=200, null=True)),
                ('Humidité', models.CharField(blank=True, max_length=2000, null=True)),
                ('Température', models.CharField(blank=True, max_length=2000, null=True)),
                ('Temps_de_Séchage', models.CharField(blank=True, max_length=2000, null=True)),
                ('Date_Debut', models.DateTimeField(blank=True, null=True)),
                ('Date_Fin', models.DateTimeField(blank=True, null=True)),
                ('N_Lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='saisir.lot')),
            ],
        ),
        migrations.CreateModel(
            name='SachetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operateur', models.CharField(blank=True, max_length=200, null=True)),
                ('Quantité', models.FloatField(blank=True, null=True)),
                ('Cadence', models.FloatField(blank=True, null=True)),
                ('Date_Debut', models.DateTimeField(blank=True, null=True)),
                ('Date_Fin', models.DateTimeField(blank=True, null=True)),
                ('Rendement', models.CharField(blank=True, max_length=200, null=True)),
                ('N_Lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='saisir.lot')),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('Non Sensible', 'Non Sensible'), ('Sensible', 'Sensible')], max_length=200)),
                ('forme', models.CharField(blank=True, max_length=2000, null=True)),
                ('quantité', models.FloatField(blank=True, null=True)),
                ('n_sac', models.IntegerField(blank=True, null=True)),
                ('emplacement', models.CharField(blank=True, max_length=200, null=True)),
                ('agent', models.CharField(blank=True, max_length=200, null=True)),
                ('d_sortie', models.DateTimeField(blank=True, null=True)),
                ('d_entre', models.DateTimeField(blank=True, null=True)),
                ('qu', models.FloatField(blank=True, null=True)),
                ('N_Lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='saisir.lot')),
            ],
        ),
        migrations.CreateModel(
            name='PsfModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('Non Sensible', 'Non Sensible'), ('Sensible', 'Sensible')], max_length=200)),
                ('Forme', models.CharField(choices=[('Comprimés Peliculés', 'Comprimés Peliculés'), ('Gellules', 'Gellules'), ('Comprimés nus', 'Comprimés nus')], max_length=200)),
                ('Quantité', models.FloatField(blank=True, null=True)),
                ('N_sac', models.IntegerField(blank=True, null=True)),
                ('Emplacement', models.CharField(blank=True, max_length=200, null=True)),
                ('Agent', models.CharField(blank=True, max_length=200, null=True)),
                ('D_sortie', models.DateTimeField(blank=True, null=True)),
                ('D_entre', models.DateTimeField(blank=True, null=True)),
                ('qu', models.FloatField(blank=True, null=True)),
                ('N_Lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='saisir.lot')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_Produit', models.CharField(max_length=1000)),
                ('Produit', models.CharField(max_length=1000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('N_Lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='saisir.lot')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='PesageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(blank=True, max_length=200, null=True)),
                ('Matiere_Non_Pesée', models.TextField(blank=True, max_length=2000, null=True)),
                ('Quantité', models.FloatField(blank=True, null=True)),
                ('Date_Debut', models.DateTimeField(blank=True, null=True)),
                ('Date_Fin', models.DateTimeField(blank=True, null=True)),
                ('N_Lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='saisir.lot')),
            ],
        ),
        migrations.CreateModel(
            name='PeliculageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operateur', models.CharField(blank=True, max_length=200, null=True)),
                ('Quantité', models.CharField(blank=True, max_length=2000, null=True)),
                ('Date_Debut', models.DateTimeField(blank=True, null=True)),
                ('Date_Fin', models.DateTimeField(blank=True, null=True)),
                ('Rendement', models.CharField(blank=True, max_length=200, null=True)),
                ('N_Lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='saisir.lot')),
            ],
        ),
        migrations.CreateModel(
            name='MouillageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(blank=True, max_length=200, null=True)),
                ('Quantité', models.CharField(blank=True, max_length=2000, null=True)),
                ('Date_Debut', models.DateTimeField(blank=True, null=True)),
                ('Date_Fin', models.DateTimeField(blank=True, null=True)),
                ('N_Lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='saisir.lot')),
            ],
        ),
        migrations.CreateModel(
            name='MiseEnFlaconModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operateur', models.CharField(blank=True, max_length=200, null=True)),
                ('Quantité', models.FloatField(blank=True, null=True)),
                ('Cadence', models.FloatField(blank=True, null=True)),
                ('Date_Debut', models.DateTimeField(blank=True, null=True)),
                ('Date_Fin', models.DateTimeField(blank=True, null=True)),
                ('Rendement', models.CharField(blank=True, max_length=200, null=True)),
                ('N_Lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='saisir.lot')),
            ],
        ),
        migrations.CreateModel(
            name='MiseEnBlisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operateur', models.CharField(blank=True, max_length=200, null=True)),
                ('Quantité', models.FloatField(blank=True, null=True)),
                ('Cadence', models.FloatField(blank=True, null=True)),
                ('Date_Debut', models.DateTimeField(blank=True, null=True)),
                ('Date_Fin', models.DateTimeField(blank=True, null=True)),
                ('Rendement', models.CharField(blank=True, max_length=200, null=True)),
                ('N_Lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='saisir.lot')),
            ],
        ),
        migrations.CreateModel(
            name='MelangeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operateur', models.CharField(blank=True, max_length=200, null=True)),
                ('Quantité', models.FloatField(blank=True, null=True)),
                ('Date_Debut', models.DateTimeField(blank=True, null=True)),
                ('Date_Fin', models.DateTimeField(blank=True, null=True)),
                ('Rendement', models.CharField(blank=True, max_length=200, null=True)),
                ('N_Lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='saisir.lot')),
            ],
        ),
        migrations.CreateModel(
            name='GranulatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operateur', models.CharField(blank=True, max_length=200, null=True)),
                ('Poids_des_granulés_calibrés', models.FloatField(blank=True, null=True)),
                ('Poids_théorique', models.FloatField(blank=True, max_length=200, null=True)),
                ('Date_Debut', models.DateTimeField(blank=True, max_length=200, null=True)),
                ('Date_Fin', models.DateTimeField(blank=True, max_length=200, null=True)),
                ('Rendement', models.CharField(blank=True, max_length=200, null=True)),
                ('N_Lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='saisir.lot')),
            ],
        ),
        migrations.CreateModel(
            name='GeluleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operateur', models.CharField(blank=True, max_length=200, null=True)),
                ('Quantité', models.FloatField(blank=True, null=True)),
                ('Cadence', models.FloatField(blank=True, null=True)),
                ('Date_Debut', models.DateTimeField(blank=True, null=True)),
                ('Date_Fin', models.DateTimeField(blank=True, null=True)),
                ('Rendement', models.CharField(blank=True, max_length=200, null=True)),
                ('N_Lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='saisir.lot')),
            ],
        ),
        migrations.CreateModel(
            name='DoublePesageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(blank=True, max_length=200, null=True)),
                ('Quantité', models.FloatField(blank=True, null=True)),
                ('Date_Debut', models.DateTimeField(blank=True, null=True)),
                ('Date_Fin', models.DateTimeField(blank=True, null=True)),
                ('N_Lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='saisir.lot')),
            ],
        ),
        migrations.CreateModel(
            name='CompressionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operateur', models.CharField(blank=True, max_length=200, null=True)),
                ('Quantité', models.FloatField(blank=True, null=True)),
                ('Cadence', models.FloatField(blank=True, null=True)),
                ('Date_Debut', models.DateTimeField(blank=True, null=True)),
                ('Date_Fin', models.DateTimeField(blank=True, null=True)),
                ('Rendement', models.CharField(blank=True, max_length=200, null=True)),
                ('N_Lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='saisir.lot')),
            ],
        ),
        migrations.CreateModel(
            name='CalibrageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operateur', models.CharField(blank=True, max_length=2000, null=True)),
                ('Tamis', models.CharField(blank=True, max_length=2000, null=True)),
                ('Date_Debut', models.DateTimeField(blank=True, null=True)),
                ('Date_Fin', models.DateTimeField(blank=True, null=True)),
                ('N_Lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='saisir.lot')),
            ],
        ),
    ]
